package gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.Slider;

public class TipCalculatorController {
	@FXML
	private Label label1;
	@FXML
	private Label label2;
	@FXML
	private Label label3;
	@FXML
	private Label label4;
	@FXML
	private TextField textfield1;
	@FXML
	private TextField textfield2;
	@FXML
	private TextField textfield3;
	@FXML
	private Slider slider1;
	@FXML
	private Button button1;

	// Event Listener on Button[#button1].onAction
	@FXML
	public void calculateButtonPressed(ActionEvent event) {
		// TODO Autogenerated
	}
}
